# Generated by Django 4.2.3 on 2023-07-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_death', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('is_alive', models.BooleanField(null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('movements', models.ManyToManyField(blank=True, to='ia_art.movement')),
            ],
        ),
    ]
