# Generated by Django 4.2.3 on 2023-07-14 16:13

from django.db import migrations, models
import django.db.models.deletion
import ia_art.models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_art', '0002_painting_artist_paintings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ia_art/midjourney/', validators=[ia_art.models.validate_image_size])),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='midjourney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ia_art.midjourney'),
        ),
    ]
